# **Introduction to OpenCV**

These set of notebooks correspond to the tutorial provided by [ProgrammingKnowldge](https://www.youtube.com/channel/UCs6nmQViDpUw0nuIx9c_WvA) YouTube channel which consists of a series of videos as a way of introducing OpenCV with Python. You can also check the full tutorial (around 9 hours and 23 minutes of length) at the following [link](https://www.youtube.com/watch?v=N81PCpADwKQ).

In this particular notebook, we'll see an introduction to OpenCV, including:

- How to read, write and show images on OpenCV
- How to read, write and show videos using cameras
- Drawing geometric shapes on camera

## **1. What is OpenCV?**

First of all, OpenCV is an open source Computer Vision library. 

Computer Vision "*is the field of computer science that focuses on replicating parts of the complexity of the human vision system and enabling computers to identify and process objects in images and videos in the same way that humans do*". Is what allows cimputers to see and process data as humans do.

## **2. How do computers see images?**

Images are represented as matrixes defined by the height and width of pixels the images is composed. Also, we have `grey-scaled images` which are represented by only one matrix of of these pixels (one numerical value for each pixel) and `colored images` which allows to represent more real images. The latter ones are composed by three matrixes in which each of these represent one of the basic colors humans see: red, yellow and blue.


## **3. Manipulating Images**

First, we'll have to import OpenCV, and let's also check the version installed.


In [1]:
import cv2

print(cv2.__version__)

4.5.1


Now, to make easier the import of the images lets change the current directory to where the files are stored.

In [2]:
import os

os.getcwd()

'C:\\Users\\Aristi\\Documents\\Cursos\\OpenCV'

In [3]:
path = 'C:\\Users\\Aristi\\Documents\\Cursos\\OpenCV\\SampleImages'
os.chdir(path)

### **3.1 Reading images**

Let's see how we can read images by using the `imread()` method. The first argument is the image to load, the second specifies the way the image should be read: 1 corresponds to colored image, 0 corresponds to grayscale image and -1 loads the image unchanged (including alpha channels that are several transformations that an image can have such as transparency).

Also, in order to show the images we are importing we can use the `imshow()` method. Where the first argument of the method is the name of the window in which your image will be opened and the second argument should be the image (generally assigned in a variable).

As this method appeared to crash on Google Colab, we are using the `cv2_imshow()` from the `google.colab.patches` library.

In [4]:
img_1 = cv2.imread('lena.jpg',1)

cv2.imshow('colored-image',img_1)
quit_img = cv2.waitKey(0)

if quit_img == 27:  # Quitting with 'esc' key
    cv2.destroyAllWindows()

In [5]:
img_2 = cv2.imread('lena.jpg',0)

cv2.imshow('colored-image',img_2)
quit_img = cv2.waitKey(0)

if quit_img == 27:  # Quitting with 'esc' key
    cv2.destroyAllWindows()

### **3.2 Writing images**

For writing an image, we are using the `imwrite()` method that works similarly as the reading method.

In [6]:
cv2.imwrite('lena-copy.png', img_2)

True

The 'true' value above shows that the operation was done succesfully. So the image was saved with the name 'lena-copy.png' in the current directory.

## **4. Manipulating videos using cameras**

These methods will work with both live cameras and videos that are stored as a file.


### **4.1 Reading a video**

In both cases we will be using the  `VideoCapture()` method, in which if we enter the name of the video file we want to read, that would captured. Instead, if we want to use our own camera, we have to add as the argument the index of the camera we want to used that by default it's either 0 or -1 (these are equivalent). Also if we want to use several cameras we can use 1 or 2 for the second camera as the argument and so on.

In [7]:
cap = cv2.VideoCapture(0)

In order to capture the frame continuosly we have to make a while loop. The `read` method that we'll be using will return `True` if the frame is available and the frame will be saved in the following frame variable.

Also, we have to invoke again the `imshow()` method for showing the video that is being captured.

For being able to stop the video capturing, we'll use the `destroyAllWindows()` method that will respond after the `waitKey()`. It's important also to release the resources used, that can be done with `.release()`

In [8]:
cap = cv2.VideoCapture(0)

while (True):
    ret, frame = cap.read()
    cv2.imshow('frame_name', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

We can also make the video captured grey defining a new variable with the method `cvtColor()` where the first argument is the source video and the second argument is the conversion we want to do.

In [9]:
cap = cv2.VideoCapture(0)

while (True):
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('frame_name', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Let's see one more example but with a file stored within a folder:

In [10]:
cap = cv2.VideoCapture('vtest.avi')

while (True):
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('frame_name', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

By using this `cap` instance you can read some properties of the video that is being captured. 

The first we're going to see is if the video is opened or not. This method is `isOpened()`. This is usually used for avoiding giving the wrong file name or the wrong camera number (as it is going to return False).

Another property is the `get()` method, where we can provide the property id and assign it into a variable. For example, for obtaining the width (`CAP_PROP_FRAME_WIDTH`) and the height (`CAP_PROP_FRAME_HEIGHT`).

You may also find the full description of propoerties in the [OpenCV Documentation > VideoCaptureProperties](https://docs.opencv.org/3.4/d4/d15/group__videoio__flags__base.html#gaeb8dd9c89c10a5c63c139bf7c4f5704d)

In [13]:
cap = cv2.VideoCapture(0)
aux = 0   # This is for obtaining the props just once

while (cap.isOpened()):
    ret, frame = cap.read()
    
    if aux == 0:
        print('Frame width: ', cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print('Frame height: ', cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        aux += 1
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('frame_name', gray)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Frame width:  640.0
Frame width:  480.0


### **4.2 Writing / Saving a video**

We can save videos using the `VideoWriter()` class, in which the first argument is the name we want to give to the file. 

The second argument is the fourcc code is used for specifying the video codec (is software or hardware that compresses and decompresses digital video). These can be found on the [fourcc webpage](https://www.fourcc.org/codecs.php). We can initialize the fourcc with the `VideoWriter_fourcc()` method.

The third argument is the number of FPS (frames per second).

The fourth argument is the size of the frames, which we already know that we are capturing in (640, 480) pixels' frames.

In [14]:
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))

while (cap.isOpened()):
    ret, frame = cap.read()
    
    if ret == True:
        out.write(frame)
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame_name', gray)
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

Notice that this video will be saved in the BGR colored frame because we used the 'frame' variable in the output.